spring:
  application:
    name: rent-insight

  datasource:
    # MySQL ?? ??
    url: jdbc:mysql://localhost:3306/rentinsight?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=UTF-8
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    # ?? ??(Entity)? ???? DB ??? ?? ??/??
    hibernate:
      ddl-auto: update
    # ???? ???? SQL? ??? ??
    show-sql: true
    properties:
      hibernate:
        format_sql: true